# Generated by Django 2.1.5 on 2020-04-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0017_auto_20200424_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.RemoveField(
            model_name='game',
            name='plateforms',
        ),
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='games',
        ),
        migrations.AlterField(
            model_name='gamer',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='gamers.Friend_Request'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='friends',
            field=models.ManyToManyField(blank=True, to='gamers.Friend'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='gamers.Notification'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
