# Generated by Django 2.1.5 on 2020-04-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0019_auto_20200424_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='friend_requests',
            field=models.ManyToManyField(to='gamers.Friend_Request'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='friends',
            field=models.ManyToManyField(to='gamers.Friend'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='games',
            field=models.ManyToManyField(to='gamers.Game'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='notifications',
            field=models.ManyToManyField(to='gamers.Notification'),
        ),
    ]
