# Generated by Django 2.1.5 on 2020-04-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0021_auto_20200424_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(blank=True, to='gamers.Gamer_ID'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='gamers.Friend_Request'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='friends',
            field=models.ManyToManyField(blank=True, to='gamers.Friend'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='games',
            field=models.ManyToManyField(blank=True, to='gamers.Game'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='gamers.Notification'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='pp',
            field=models.ImageField(blank=True, null=True, upload_to='pp/'),
        ),
    ]
