# Generated by Django 2.1.5 on 2020-04-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0023_remove_friend_request_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend_Request_Status',
        ),
    ]
