# Generated by Django 2.1.5 on 2020-04-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0025_gamer_my_friend_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='friend_requests',
            new_name='sent_friend_requests',
        ),
    ]
