# Generated by Django 2.1.5 on 2020-04-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0028_auto_20200428_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='second_user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
