# Generated by Django 2.1.5 on 2020-04-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0024_delete_friend_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='my_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='my_friend_request_user', to='gamers.Friend_Request'),
        ),
    ]
